### ISSUE TITLE
Bridging assets to a different owned address

### ISSUE THREAD

**Issue by arikan** [ava-labs/avalanche-bridge-resources#43]
The current Avalanche Bridge (https://core.app/bridge) only supports asset bridging between identical addresses on Ethereum and C-chain controlled by the user. It does not permit bridging to a different address, even if owned by the same user.

This limitation poses an issue. For instance, if I use a new "Account Abstraction" wallet or an embedded (MPC) wallet for an app, and I want to bridge assets from Ethereum directly to this wallet, the platform doesn't allow it in a single step. However, allowing asset bridging to another address controlled by the user doesn't significantly elevate the risk.

Therefore, it would be beneficial if Avalanche Bridge could enable asset bridging to different addresses on the receiving chain, provided they are owned by the user.

**Comment by michaelkaplan13** [comment]
Thanks for submitting this request, and sorry we did not see it until now.

The Avalanche Bridge backend only allows for transferring assets between the same wallet on both chains (including Bitcoin), primarily for regulatory reasons. MPC wallets should theoretically be possible to use still, since they present as any other EOA on chain), but totally recognize that this limitation prohibits account abstraction and other possibilities.
